--create table if not exists persistent_logins (
--     username varchar(100) not null,
--     series varchar(64) primary key,
--     token varchar(64) not null,
--     last_used timestamp not null
--);
--
--
--delete from  user_role;
--
--
--delete from  roles;
--
--
--delete from  users;
--
--
--
--INSERT INTO roles (id, name) VALUES
--(1, 'ROLE_ADMIN'),
--(2, 'ROLE_ACTUATOR'),
--(3, 'ROLE_USER');
--
--
--INSERT INTO users (id, email, password, name,phone_number,gender) VALUES
--(1, 'admin@gmail.com', '$2a$10$hKDVYxLefVHV/vtuPhWD3OigtRyOykRLDdUAp80Z1crSoS1lFqaFS', 'Admin','0782602874','male'),
--(2, 'abood.alhmouz121@gmail.com', '$2a$10$ByIUiNaRfBKSV6urZoBBxe4UbJ/sS6u1ZaPORHF9AtNWAuVPVz1by', 'User1','0782602874','male'),
--(3, 'user@gmail.com', '$2a$10$ByIUiNaRfBKSV6urZoBBxe4UbJ/sS6u1ZaPORHF9AtNWAuVPVz1by', 'User','0782602874','male');
--
--insert into user_role(user_id, role_id) values
--(1,1),
--(1,2),
--(1,3),
--(3,2);
--
--insert into groups(id, instructor_name) values
--(1,'abdalrahman_alhmouz'),
--(2,'sawsan'),
--(3,'amneh');
--
--insert into user_group(user_id, group_id) values
--(1,1),
--(3,2);
